# 데이콘 농산물 가격예측

## 1. 농산물 가격 예측 

주소 : https://dacon.io/edu/21025/1

In [2]:
import pandas as pd
import numpy as np

In [3]:
train = pd.read_csv('public_data/train.csv')

In [4]:
train

,date,요일,배추_거래량(kg),배추_가격(원/kg),무_거래량(kg),무_가격(원/kg),양파_거래량(kg),양파_가격(원/kg),건고추_거래량(kg),건고추_가격(원/kg),...,청상추_거래량(kg),청상추_가격(원/kg),백다다기_거래량(kg),백다다기_가격(원/kg),애호박_거래량(kg),애호박_가격(원/kg),캠벨얼리_거래량(kg),캠벨얼리_가격(원/kg),샤인마스캇_거래량(kg),샤인마스캇_가격(원/kg)
0,2016-01-01,금요일,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2016-01-02,토요일,80860.0,329.0,80272.0,360.0,122787.5,1281.0,3.0,11000.0,...,5125.0,9235.0,434.0,2109.0,19159.0,2414.0,880.0,2014.0,0.0,0.0
2,2016-01-03,일요일,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2016-01-04,월요일,1422742.5,478.0,1699653.7,382.0,2315079.0,1235.0,699.0,4464.0,...,38525.5,7631.0,500702.0,2046.0,620539.0,2018.0,2703.8,3885.0,0.0,0.0
4,2016-01-05,화요일,1167241.0,442.0,1423482.3,422.0,2092960.1,1213.0,1112.6,4342.0,...,32615.0,6926.0,147638.0,2268.0,231958.0,2178.0,8810.0,2853.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1728,2020-09-24,목요일,1856965.0,1839.0,2055640.0,990.0,2281429.2,990.0,2818.4,19101.0,...,50730.0,4509.0,282212.3,3001.0,313139.7,3426.0,504242.6,3620.0,283196.9,10940.0
1729,2020-09-25,금요일,1880095.5,1789.0,1879261.0,1011.0,2074513.0,955.0,1887.1,23095.0,...,54322.0,4178.0,312214.8,2999.0,362741.0,3357.0,479683.1,3618.0,303779.6,10844.0
1730,2020-09-26,토요일,1661090.9,1760.0,1709385.7,1075.0,2089081.2,961.0,959.0,22510.0,...,61213.0,3770.0,327395.8,3065.0,390361.2,3092.0,521493.8,3691.0,313295.7,10636.0
1731,2020-09-27,일요일,25396.0,3066.0,38222.0,1139.0,18240.0,1056.0,60.0,22333.0,...,144.0,4076.0,285.0,3707.0,2464.0,3252.0,21717.0,3567.0,9734.0,10699.0
1732,2020-09-28,월요일,2405051.9,1867.0,2747519.5,1147.0,2235784.7,964.0,1630.6,22022.0,...,84155.0,4167.0,554862.6,2873.0,667745.0,2782.0,601841.0,3761.0,382263.4,10998.0

## 2. 날짜 범위 확인

In [5]:
train_min_date = train['date'].min()
train_max_date = train['date'].max()

display(f"train 데이터 기간 : {train_min_date} ~ {train_max_date}")

'train 데이터 기간 : 2016-01-01 ~ 2020-09-28'

## 3. 제출파일 형식 확인

In [6]:
submission = pd.read_csv('sample_submission.csv')

In [7]:
submission

,예측대상일자,배추_가격(원/kg),무_가격(원/kg),양파_가격(원/kg),건고추_가격(원/kg),마늘_가격(원/kg),대파_가격(원/kg),얼갈이배추_가격(원/kg),양배추_가격(원/kg),깻잎_가격(원/kg),...,당근_가격(원/kg),파프리카_가격(원/kg),새송이_가격(원/kg),팽이버섯_가격(원/kg),토마토_가격(원/kg),청상추_가격(원/kg),백다다기_가격(원/kg),애호박_가격(원/kg),캠벨얼리_가격(원/kg),샤인마스캇_가격(원/kg)
0,2020-09-29+1week,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2020-09-29+2week,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2020-09-29+4week,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2020-09-30+1week,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2020-09-30+2week,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223,2021-11-03+2week,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
224,2021-11-03+4week,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
225,2021-11-04+1week,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
226,2021-11-04+2week,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
227,2021-11-04+4week,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

제출형식이 다음과 같음 <br>
그래서 나이브 예측 모델 실습을 위해서 day1과 day2를 따로 가져옴 <br>

## 4. 첫날, 둘째날 테스트 데이터 불러오기

0번째와 2번째의 값이 0이어서 3,4번째의 행을 불러왔다.<br>
이 데이터를 기반으로 1주,2주, 4주 후의 농산물 가격을 예측해보자.<br>
그리고 이 예측 결과 형식을 sample_submission 형식에 맞춰보자

In [13]:
train_day1 = train.iloc[3]
train_day2 = train.iloc[4]
display("첫째날 :")
display(train_day1)
display("둘째날 :")
display(train_day2)

'첫째날 :'

date              2016-01-04
요일                       월요일
배추_거래량(kg)         1422742.5
배추_가격(원/kg)            478.0
무_거래량(kg)          1699653.7
무_가격(원/kg)             382.0
양파_거래량(kg)         2315079.0
양파_가격(원/kg)           1235.0
건고추_거래량(kg)            699.0
건고추_가격(원/kg)          4464.0
마늘_거래량(kg)          141638.0
마늘_가격(원/kg)           5210.0
대파_거래량(kg)          994328.1
대파_가격(원/kg)           1716.0
얼갈이배추_거래량(kg)       262615.5
얼갈이배추_가격(원/kg)        1212.0
양배추_거래량(kg)        1074699.1
양배추_가격(원/kg)           345.0
깻잎_거래량(kg)          122613.5
깻잎_가격(원/kg)           9923.0
시금치_거래량(kg)         427435.1
시금치_가격(원/kg)          2153.0
미나리_거래량(kg)          82113.5
미나리_가격(원/kg)          3960.0
당근_거래량(kg)          558950.2
당근_가격(원/kg)            794.0
파프리카_거래량(kg)        104930.3
파프리카_가격(원/kg)         4871.0
새송이_거래량(kg)         277326.5
새송이_가격(원/kg)          2440.0
팽이버섯_거래량(kg)        159800.0
팽이버섯_가격(원/kg)         1750.0
토마토_거래량(kg)         291057.0
토마토_가격(원/kg)          1834.0
청상추_거래량(kg)          38525.5
청상추_가격(원/kg)          7631.0
백다다기_거래량(kg)        500702.0
백다다기_가격(원/kg)         2046.0
애호박_거래량(kg)         620539.0
애호박_가격(원/kg)          2018.0
캠벨얼리_거래량(kg)          2703.8
캠벨얼리_가격(원/kg)         3885.0
샤인마스캇_거래량(kg)            0.0
샤인마스캇_가격(원/kg)           0.0
Name: 3, dtype: object

'둘째날 :'

date              2016-01-05
요일                       화요일
배추_거래량(kg)         1167241.0
배추_가격(원/kg)            442.0
무_거래량(kg)          1423482.3
무_가격(원/kg)             422.0
양파_거래량(kg)         2092960.1
양파_가격(원/kg)           1213.0
건고추_거래량(kg)           1112.6
건고추_가격(원/kg)          4342.0
마늘_거래량(kg)          126207.8
마늘_가격(원/kg)           5387.0
대파_거래량(kg)          787716.0
대파_가격(원/kg)           1715.0
얼갈이배추_거래량(kg)       221850.5
얼갈이배추_가격(원/kg)        1197.0
양배추_거래량(kg)         825681.9
양배추_가격(원/kg)           350.0
깻잎_거래량(kg)           79055.9
깻잎_가격(원/kg)           9529.0
시금치_거래량(kg)         334636.8
시금치_가격(원/kg)          2220.0
미나리_거래량(kg)          80144.0
미나리_가격(원/kg)          3333.0
당근_거래량(kg)          444353.7
당근_가격(원/kg)            763.0
파프리카_거래량(kg)        100699.5
파프리카_가격(원/kg)         5129.0
새송이_거래량(kg)         218465.2
새송이_가격(원/kg)          2437.0
팽이버섯_거래량(kg)        153084.0
팽이버섯_가격(원/kg)         1822.0
토마토_거래량(kg)         194626.5
토마토_가격(원/kg)          1833.0
청상추_거래량(kg)          32615.0
청상추_가격(원/kg)          6926.0
백다다기_거래량(kg)        147638.0
백다다기_가격(원/kg)         2268.0
애호박_거래량(kg)         231958.0
애호박_가격(원/kg)          2178.0
캠벨얼리_거래량(kg)          8810.0
캠벨얼리_가격(원/kg)         2853.0
샤인마스캇_거래량(kg)            0.0
샤인마스캇_가격(원/kg)           0.0
Name: 4, dtype: object

## 5. 첫째날 데이터를 기반으로 Naive forcasting 하여 제출 파일 생성하기
생성한 train_day1의 데이터를 기반으로 나이브 예측을 해보자!

In [18]:
# 빈 submission_day1 DataFrame 생성
submission_day1 = pd.DataFrame(columns = submission.columns)

# train_day1 의 정보가져오기
date = train_day1['date']
# date라는 것을 날짜를 가져오는 형식으로 저장해놓음

# 예측대상일자 추가
submission_day1['예측대상일자'] = [f'{date}+1week',f'{date}+2week',f'{date}+4week']
# f-string을 이용하여 예측대상일자를 표시해놓음

target_items = submission_day1.columns[1:]

In [19]:
submission_day1

,예측대상일자,배추_가격(원/kg),무_가격(원/kg),양파_가격(원/kg),건고추_가격(원/kg),마늘_가격(원/kg),대파_가격(원/kg),얼갈이배추_가격(원/kg),양배추_가격(원/kg),깻잎_가격(원/kg),...,당근_가격(원/kg),파프리카_가격(원/kg),새송이_가격(원/kg),팽이버섯_가격(원/kg),토마토_가격(원/kg),청상추_가격(원/kg),백다다기_가격(원/kg),애호박_가격(원/kg),캠벨얼리_가격(원/kg),샤인마스캇_가격(원/kg)
0,2016-01-04+1week,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2016-01-04+2week,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2016-01-04+4week,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
for item in target_items:
    last_observation = train_day1[item]
    
    submission_day1.loc[submission_day1['예측대상일자'] == f'{date}+1week', item] = last_observation
    submission_day1.loc[submission_day1['예측대상일자'] == f'{date}+2week', item] = last_observation
    submission_day1.loc[submission_day1['예측대상일자'] == f'{date}+4week', item] = last_observation

In [25]:
submission_day1

,예측대상일자,배추_가격(원/kg),무_가격(원/kg),양파_가격(원/kg),건고추_가격(원/kg),마늘_가격(원/kg),대파_가격(원/kg),얼갈이배추_가격(원/kg),양배추_가격(원/kg),깻잎_가격(원/kg),...,당근_가격(원/kg),파프리카_가격(원/kg),새송이_가격(원/kg),팽이버섯_가격(원/kg),토마토_가격(원/kg),청상추_가격(원/kg),백다다기_가격(원/kg),애호박_가격(원/kg),캠벨얼리_가격(원/kg),샤인마스캇_가격(원/kg)
0,2016-01-04+1week,478.0,382.0,1235.0,4464.0,5210.0,1716.0,1212.0,345.0,9923.0,...,794.0,4871.0,2440.0,1750.0,1834.0,7631.0,2046.0,2018.0,3885.0,0.0
1,2016-01-04+2week,478.0,382.0,1235.0,4464.0,5210.0,1716.0,1212.0,345.0,9923.0,...,794.0,4871.0,2440.0,1750.0,1834.0,7631.0,2046.0,2018.0,3885.0,0.0
2,2016-01-04+4week,478.0,382.0,1235.0,4464.0,5210.0,1716.0,1212.0,345.0,9923.0,...,794.0,4871.0,2440.0,1750.0,1834.0,7631.0,2046.0,2018.0,3885.0,0.0

당연히 값이 하나니까

### 똑같이 day2도 해주자

In [26]:
# 빈 submission_day1 DataFrame 생성
submission_day2 = pd.DataFrame(columns = submission.columns)

# train_day1 의 정보가져오기
date = train_day1['date']
# date라는 것을 날짜를 가져오는 형식으로 저장해놓음

# 예측대상일자 추가
submission_day2['예측대상일자'] = [f'{date}+1week',f'{date}+2week',f'{date}+4week']
# f-string을 이용하여 예측대상일자를 표시해놓음

target_items = submission_day2.columns[1:]

In [27]:
for item in target_items:
    last_observation = train_day1[item]
    submission_day2[item] = last_observation

In [28]:
# submission_day1 과 submission_day2 결합
final_submission = pd.concat([submission_day1, submission_day2]).reset_index(drop=True)

display(final_submission)

,예측대상일자,배추_가격(원/kg),무_가격(원/kg),양파_가격(원/kg),건고추_가격(원/kg),마늘_가격(원/kg),대파_가격(원/kg),얼갈이배추_가격(원/kg),양배추_가격(원/kg),깻잎_가격(원/kg),...,당근_가격(원/kg),파프리카_가격(원/kg),새송이_가격(원/kg),팽이버섯_가격(원/kg),토마토_가격(원/kg),청상추_가격(원/kg),백다다기_가격(원/kg),애호박_가격(원/kg),캠벨얼리_가격(원/kg),샤인마스캇_가격(원/kg)
0,2016-01-04+1week,478.0,382.0,1235.0,4464.0,5210.0,1716.0,1212.0,345.0,9923.0,...,794.0,4871.0,2440.0,1750.0,1834.0,7631.0,2046.0,2018.0,3885.0,0.0
1,2016-01-04+2week,478.0,382.0,1235.0,4464.0,5210.0,1716.0,1212.0,345.0,9923.0,...,794.0,4871.0,2440.0,1750.0,1834.0,7631.0,2046.0,2018.0,3885.0,0.0
2,2016-01-04+4week,478.0,382.0,1235.0,4464.0,5210.0,1716.0,1212.0,345.0,9923.0,...,794.0,4871.0,2440.0,1750.0,1834.0,7631.0,2046.0,2018.0,3885.0,0.0
3,2016-01-04+1week,478.0,382.0,1235.0,4464.0,5210.0,1716.0,1212.0,345.0,9923.0,...,794.0,4871.0,2440.0,1750.0,1834.0,7631.0,2046.0,2018.0,3885.0,0.0
4,2016-01-04+2week,478.0,382.0,1235.0,4464.0,5210.0,1716.0,1212.0,345.0,9923.0,...,794.0,4871.0,2440.0,1750.0,1834.0,7631.0,2046.0,2018.0,3885.0,0.0
5,2016-01-04+4week,478.0,382.0,1235.0,4464.0,5210.0,1716.0,1212.0,345.0,9923.0,...,794.0,4871.0,2440.0,1750.0,1834.0,7631.0,2046.0,2018.0,3885.0,0.0